#!/bin/bash

set -e

cd host
sterling --extensibella -I ../../ exactEval:host
../../../../../buildTools/main_to_html_extensibella.py 3 host "Extensibella Example:  exactEval:host" host.xthm syntax.sos vars.sos scopes.sos typing.sos eval.sos
extensibella --compile host.xthm
cd ..

cd ascription
sterling --extensibella -I ../../ exactEval:ascription
../../../../../buildTools/main_to_html_extensibella.py 3 ascription "Extensibella Example:  exactEval:ascription" ascription.xthm ascription.sos
cd ..

cd assert
sterling --extensibella -I ../../ exactEval:assert
../../../../../buildTools/main_to_html_extensibella.py 3 assert "Extensibella Example:  exactEval:assert" assert.xthm defs.sos
cd ..

cd condExpr
sterling --extensibella -I ../../ exactEval:condExpr
../../../../../buildTools/main_to_html_extensibella.py 3 condExpr "Extensibella Example:  exactEval:condExpr" condExpr.xthm syntax.sos
cd ..

cd list
sterling --extensibella -I ../../ exactEval:list
../../../../../buildTools/main_to_html_extensibella.py 3 list "Extensibella Example:  exactEval:list" list.xthm syntax.sos vars.sos typing.sos eval.sos
cd ..

cd security
sterling --extensibella -I ../../ exactEval:security
../../../../../buildTools/main_to_html_extensibella.py 3 security "Extensibella Example:  exactEval:security" security.xthm syntax.sos analysis.sos
cd ..

cd translation
sterling --extensibella -I ../../ exactEval:translation
../../../../../buildTools/main_to_html_extensibella.py 3 translation "Extensibella Example:  exactEval:translation" translation.xthm translation.sos
cd ..
