#!/bin/bash

cd host
../../../../buildTools/main_to_html_sterling.py 3 host.html "Sterling Example:  tutorial:host" syntax.sos closed.sos eval.sos
cd ..

cd let
../../../../buildTools/main_to_html_sterling.py 3 let.html "Sterling Example:  tutorial:let" syntax.sos
cd ..

cd typing
../../../../buildTools/main_to_html_sterling.py 3 typing.html "Sterling Example:  tutorial:typing" syntax.sos typing.sos
cd ..

cd num
../../../../buildTools/main_to_html_sterling.py 3 num.html "Sterling Example:  tutorial:num" syntax.sos
cd ..
