#!/bin/bash

cd host
../../../../buildTools/main_to_html_extensibella.py 3 host "Extensibella Example:  walkthrough:host" host.xthm def.sos
cd ..

cd let
../../../../buildTools/main_to_html_extensibella.py 3 let "Extensibella Example:  walkthrough:let" let.xthm def.sos
cd ..

cd pair
../../../../buildTools/main_to_html_extensibella.py 3 pair "Extensibella Example:  walkthrough:pair" pair.xthm def.sos
cd ..
