#!/bin/bash

set -eu

WEB_DIR="full_web"
DO_BUILD=1
EXTENSIBELLA_DIR=
STERLING_DIR=

#save initial directory to get back in the end
START_DIR=$(pwd)


#go through arguments
while test $# -gt 0
do
    case "$1" in
        #skip the rebuild, because it is slow
        -s ) DO_BUILD=0
             ;;
        #make it into a different directory
        -n ) shift
             WEB_DIR="$1"
             ;;
        #find Extensibella and Sterling for adding their tarballs
        -ex ) shift
              EXTENSIBELLA_DIR="$1"
              ;;
        -st ) shift
              STERLING_DIR="$1"
              ;;
        #something wrong
        * ) echo "Unknown option $1"
            ;;
    esac
    shift
done


#go and rebuild all the examples
if test $DO_BUILD -gt 0; then
   cd web/extensibella/examples
   ./build
   cd ../../sterling/examples
   ./build
   cd ../../.. #get out of web/, back to repository root
fi

#clean out the web copy
rm -rf $WEB_DIR

#copy everything to the web copy
cp -R web $WEB_DIR

#go to the web copy
cd $WEB_DIR

#delete build scripts and Emacs save files because we don't want them
#on the web
find . -name "*~" -delete
find . -name "build" -delete


#build the tarballs for Extensibella examples
cd extensibella
ln -s examples extensibella-examples
tar -zcvf examples/extensibella-examples.tar.gz \
    extensibella-examples/*/*/*.sos \
    extensibella-examples/*/*/*.xthm
rm extensibella-examples

cd examples
for dir in */
do
    dir=${dir%*/} # remove the trailing "/"
    tar -zcvf $dir/$dir.tar.gz \
        $dir/*/*.sos \
        $dir/*/*.xthm
done
cd ../.. #back to built web root directory


#build the tarballs for Sterling examples
cd sterling
ln -s examples sterling-examples
tar -zcvf examples/sterling-examples.tar.gz \
    sterling-examples/*/*/*.sos #\
    #sterling-examples/*/*/*.main \
    #sterling-examples/*/*/*.conc
rm sterling-examples

cd examples
for dir in */
do
    dir=${dir%*/} # remove the trailing "/"
    tar -zcvf $dir/$dir.tar.gz \
        $dir/*/*.sos #\
        #$dir/*/*.main \
        #$dir/*/*.conc
done
cd ../.. #back to built web root directory


#get the Extensibella and Sterling tarballs
found_Extensibella=0
if [ -z "$EXTENSIBELLA_DIR" ]
then
    #try next to the repository
    if [ -d "../../extensibella" ]
    then
        cd ../../extensibella
        ./make-dist
        cd -
        cp ../../extensibella/extensibella.tar.gz extensibella/
        found_Extensibella=1
    fi
elif [ -d "$EXTENSIBELLA_DIR" ]
then
    if [ -f "$EXTENSIBELLA_DIR/make-dist" ]
    then
        cd "$EXTENSIBELLA_DIR"
        ./make-dist
        cd -
        cp "$EXTENSIBELLA_DIR/extensibella.tar.gz" extensibella/
        found_Extensibella=1
    fi
fi

found_Sterling=0
if [ -z "$STERLING_DIR" ]
then
    #try next to the repository
    if [ -d "../../sterling" ]
    then
        cd ../../sterling
        ./make-dist
        cd -
        cp ../../sterling/sterling.tar.gz sterling/
        found_Sterling=1
    fi
elif [ -d "$STERLING_DIR" ]
then
    if [ -f "$STERLING_DIR/make-dist" ]
    then
        cd "$STERLING_DIR"
        ./make-dist
        cd -
        cp "$STERLING_DIR/sterling.tar.gz" sterling/
        found_Sterling=1
    fi
fi

if [ "$found_Extensibella" -eq 0 ]
then
    echo "----------------------------------------------------------------------"
    echo "COULD NOT GET EXTENSIBELLA TARBALL; DO IT BY HAND"
    echo "----------------------------------------------------------------------"
fi
if [ "$found_Sterling" -eq 0 ]
then
    echo "----------------------------------------------------------------------"
    echo "COULD NOT GET STERLING TARBALL; DO IT BY HAND"
    echo "----------------------------------------------------------------------"
fi


#check all the files included in the website are present
cd $START_DIR
echo -e "\n\n" #space it out
./buildTools/check.py $WEB_DIR
