#!/bin/bash

set -eu

WEB_DIR="full_web"
DO_BUILD=1


#go through arguments
while test $# -gt 0
do
    case "$1" in
        #skip the rebuild, because it is slow
        -s ) DO_BUILD=0
             ;;
        #make it into a different directory
        -n ) shift
             WEB_DIR="$1"
             ;;
        #something wrong
        * ) echo "Unknown option $1"
            ;;
    esac
    shift
done


#go and rebuild all the examples
if test $DO_BUILD -gt 0; then
   cd extensibella/examples
   ./build
   cd ../sterling/examples
   ./build
   cd ../../..
fi

#copy everything to the web copy
cp -R extensibella $WEB_DIR

#go to the web copy
cd $WEB_DIR

#delete build scripts and Emacs save files because we don't want them
#on the web
find . -name "*~" -delete
find . -name "build" -delete


#build the tarballs for Extensibella examples
ln -s examples extensibella-examples
tar -zcvf examples/extensibella-examples.tar.gz \
    extensibella-examples/*/*/*.sos \
    extensibella-examples/*/*/*.xthm
rm extensibella-examples

cd examples
for dir in */
do
    dir=${dir%*/} # remove the trailing "/"
    tar -zcvf $dir/$dir.tar.gz \
        $dir/*/*.sos \
        $dir/*/*.xthm
done
cd .. #back to root web directory


#build the tarballs for Sterling examples
cd sterling
ln -s examples sterling-examples
tar -zcvf examples/sterling-examples.tar.gz \
    sterling-examples/*/*/*.sos #\
    #sterling-examples/*/*/*.main \
    #sterling-examples/*/*/*.conc
rm sterling-examples

cd examples
for dir in */
do
    dir=${dir%*/} # remove the trailing "/"
    tar -zcvf $dir/$dir.tar.gz \
        $dir/*/*.sos #\
        #$dir/*/*.main \
        #$dir/*/*.conc
done
cd ../.. #back to root directory to make adding here easier


echo "NOW GO GET THE EXTENSIBELLA AND STERLING TARBALLS AND ADD THEM"
