#!/bin/bash

set -e

cd host
sterling --extensibella -I ../../ lambda_calculus:host
../../../../../buildTools/main_to_html_extensibella.py 3 host "Extensibella Example:  lambda_calculus:host" host.xthm syntax.sos eval.sos
extensibella --compile host.xthm
cd ..

cd typing
sterling --extensibella -I ../../ lambda_calculus:typing
../../../../../buildTools/main_to_html_extensibella.py 3 typing "Extensibella Example:  lambda_calculus:typing" typing.xthm syntax.sos typing.sos
cd ..

cd bool
sterling --extensibella -I ../../ lambda_calculus:bool
../../../../../buildTools/main_to_html_extensibella.py 3 bool "Extensibella Example:  lambda_calculus:bool" bool.xthm syntax.sos eval.sos
cd ..

cd let
sterling --extensibella -I ../../ lambda_calculus:let
../../../../../buildTools/main_to_html_extensibella.py 3 let "Extensibella Example:  lambda_calculus:let" let.xthm def.sos
cd ..

cd pair
sterling --extensibella -I ../../ lambda_calculus:pair
../../../../../buildTools/main_to_html_extensibella.py 3 pair "Extensibella Example:  lambda_calculus:pair" pair.xthm def.sos
cd ..
