#!/bin/bash

set -e

cd host
../../../../../buildTools/main_to_html_sterling.py 3 host.html "Sterling Example:  soundX:host" def.sos
cd ..

cd let
../../../../../buildTools/main_to_html_sterling.py 3 let.html "Sterling Example:  soundX:let" def.sos
cd ..

cd pair
../../../../../buildTools/main_to_html_sterling.py 3 pair.html "Sterling Example:  soundX:pair" def.sos
cd ..
