#!/bin/bash

set -e

cd host
sterling --extensibella -I ../../ walkthrough:host
../../../../../buildTools/main_to_html_extensibella.py 3 host "Extensibella Example:  walkthrough:host" host.xthm def.sos
extensibella --compile host.xthm
cd ..

cd let
sterling --extensibella -I ../../ walkthrough:let
../../../../../buildTools/main_to_html_extensibella.py 3 let "Extensibella Example:  walkthrough:let" let.xthm def.sos
cd ..

cd big_step
sterling --extensibella -I ../../ walkthrough:big_step
../../../../../buildTools/main_to_html_extensibella.py 3 big_step "Extensibella Example:  walkthrough:big_step" big_step.xthm module.sos
cd ..
