#!/bin/bash

set -e

cd host
sterling --extensibella -I ../../ walkthrough:host
../../../../../buildTools/main_to_html_extensibella.py 3 host "Extensibella Example:  walkthrough:host" host.xthm def.sos
extensibella --compile host.xthm
cd ..

cd let
sterling --extensibella -I ../../ walkthrough:let
../../../../../buildTools/main_to_html_extensibella.py 3 let "Extensibella Example:  walkthrough:let" let.xthm def.sos
cd ..
