#!/bin/bash

cd lrat
../../../../buildTools/main_to_html_sterling.py 3 lrat.html "Sterling Example:  unsat_proofs:lrat" syntax.sos sat.sos check.sos
cd ..

cd drat
../../../../buildTools/main_to_html_sterling.py 3 drat.html "Sterling Example:  unsat_proofs:drat" syntax.sos check.sos toDrat.sos
cd ..

cd clauses
../../../../buildTools/main_to_html_sterling.py 3 clauses.html "Sterling Example:  unsat_proofs:clauses" syntax.sos sat.sos check.sos
cd ..

cd frat
../../../../buildTools/main_to_html_sterling.py 3 frat.html "Sterling Example:  unsat_proofs:frat" syntax.sos check.sos elaboration.sos
cd ..
