#!/bin/bash

set -e

cd host
sterling --extensibella -I ../../ stlc:host
../../../../buildTools/main_to_html_extensibella.py 2 host "Extensibella Example:  stlc:host" host.xthm def.sos
extensibella --compile host.xthm
cd ..

cd let
sterling --extensibella -I ../../ stlc:let
../../../../buildTools/main_to_html_extensibella.py 2 let "Extensibella Example:  stlc:let" let.xthm def.sos
cd ..

cd pair
sterling --extensibella -I ../../ stlc:pair
../../../../buildTools/main_to_html_extensibella.py 2 pair "Extensibella Example:  stlc:pair" pair.xthm def.sos
cd ..
