#!/bin/bash

cd lists
sterling --extensibella -I ../../ nonExtensible:lists
../../../../buildTools/main_to_html_extensibella.py 3 lists "Extensibella Example:  nonExtensible:lists" thms.xthm lists.sos
ext_exit_code=$?
if [[ $ext_exit_code -ne 0 ]] ; then
    exit 1
fi
cd ..
