#!/bin/bash

set -e

cd shared_declarations
../../../../../buildTools/main_to_html_sterling.py 3 shared_declarations.html "Sterling Example:  mtc:shared_declarations" decls.sos
cd ..

cd arith
../../../../../buildTools/main_to_html_sterling.py 3 arith.html "Sterling Example:  mtc:arith" defs.sos
cd ..

cd bool
../../../../../buildTools/main_to_html_sterling.py 3 bool.html "Sterling Example:  mtc:bool" defs.sos
cd ..

cd lambda
../../../../../buildTools/main_to_html_sterling.py 3 lambda.html "Sterling Example:  mtc:lambda" defs.sos
cd ..

cd natCase
../../../../../buildTools/main_to_html_sterling.py 3 natCase.html "Sterling Example:  mtc:natCase" defs.sos
cd ..
