#!/bin/bash

dirs=( "nonExtensible" "walkthrough" "library" "simple_imp" "lambda_calculus" "stlc" "unsat_proofs" )

for dir in "${dirs[@]}"
do
    cd "$dir"
    ./build
    #check for failure to stop here
    if [[ $? -ne 0 ]] ; then
        echo "Error processing $dir; build failed"
        exit 1
    fi
    #display the successful completion
    echo ""
    echo ""
    echo "============================================================"
    echo "************************************************************"
    echo "Built $dir"
    echo "************************************************************"
    echo "============================================================"
    echo ""
    echo ""
    cd ..
done
