#!/bin/bash

set -e

cd host
sterling --extensibella -I ../../ soundX:host
../../../../../buildTools/main_to_html_extensibella.py 3 host "Extensibella Example:  soundX:host" host.xthm def.sos
extensibella --compile host.xthm
cd ..

cd let
sterling --extensibella -I ../../ soundX:let
../../../../../buildTools/main_to_html_extensibella.py 3 let "Extensibella Example:  soundX:let" let.xthm def.sos
cd ..

cd pair
sterling --extensibella -I ../../ soundX:pair
../../../../../buildTools/main_to_html_extensibella.py 3 pair "Extensibella Example:  soundX:pair" pair.xthm def.sos
cd ..
