#!/bin/bash

cd host
../../../../../buildTools/main_to_html_sterling.py 3 host.html "Sterling Example:  modelingMSOS:host" syntax.sos eval.sos
cd ..

cd vars
../../../../../buildTools/main_to_html_sterling.py 3 vars.html "Sterling Example:  modelingMSOS:vars" vars.sos
cd ..

cd stores
../../../../../buildTools/main_to_html_sterling.py 3 stores.html "Sterling Example:  modelingMSOS:stores" stores.sos
cd ..

cd bool
../../../../../buildTools/main_to_html_sterling.py 3 bool.html "Sterling Example:  modelingMSOS:bool" bool.sos
cd ..

cd print
../../../../../buildTools/main_to_html_sterling.py 3 print.html "Sterling Example:  modelingMSOS:print" print.sos
cd ..
