#!/bin/bash

cd host
../../../../../buildTools/main_to_html_sterling.py 3 host.html "Sterling Example:  stlc:host" stlc.sos
cd ..

cd let
../../../../../buildTools/main_to_html_sterling.py 3 let.html "Sterling Example:  stlc:let" let.sos
cd ..

cd pair
../../../../../buildTools/main_to_html_sterling.py 3 pair.html "Sterling Example:  stlc:pair" pair.sos
cd ..

cd letPair
../../../../../buildTools/main_to_html_sterling.py 3 letPair.html "Sterling Example:  stlc:letPair" letPair.sos
cd ..
