#!/bin/bash

cd host
../../../../../buildTools/main_to_html_sterling.py 3 host.html "Sterling Example:  functions:host" syntax.sos vars.sos typing.sos eval.sos domains.sos
cd ..

cd list
../../../../../buildTools/main_to_html_sterling.py 3 list.html "Sterling Example:  functions:list" list.sos list_vars.sos list_typing.sos list_eval.sos
cd ..

cd security
../../../../../buildTools/main_to_html_sterling.py 3 security.html "Sterling Example:  functions:security" security.sos analysis.sos
cd ..
