#!/bin/bash

dirs=( "nonExtensible" "walkthrough" "simple_imp" "lambda_calculus" "stlc" )

for dir in "${dirs[@]}"
do
    cd "$dir"
    ./build
    echo ""
    echo ""
    echo "============================================================"
    echo "************************************************************"
    echo "Built $dir"
    echo "************************************************************"
    echo "============================================================"
    echo ""
    echo ""
    cd ..
done
