#!/bin/bash

dirs=( "walkthrough" "simple_imp" )

for dir in "${dirs[@]}"
do
    cd "$dir"
    ./build
    echo ""
    echo "************************************************************"
    echo "Built $dir"
    echo "************************************************************"
    echo ""
    cd ..
done
