#!/bin/bash

set -e

cd lists
sterling --extensibella -I ../../ nonExtensible:lists
../../../../../buildTools/main_to_html_extensibella.py 3 lists "Extensibella Example:  nonExtensible:lists" thms.xthm lists.sos
cd ..
