#!/bin/bash

cd host
../../../../buildTools/main_to_html_sterling.py 3 host.html "Sterling Example:  simple_imp:host" syntax.sos vars.sos typing.sos eval.sos
cd ..

cd list
../../../../buildTools/main_to_html_sterling.py 3 list.html "Sterling Example:  simple_imp:list" list.sos list_vars.sos list_typing.sos list_eval.sos
cd ..

cd security
../../../../buildTools/main_to_html_sterling.py 3 security.html "Sterling Example:  simple_imp:security" security.sos analysis.sos
cd ..

cd repeatWhile
../../../../buildTools/main_to_html_sterling.py 3 repeatWhile.html "Sterling Example:  simple_imp:repeatWhile" repeatWhile.sos
cd ..
