#!/bin/bash

cd host
sterling --extensibella -I ../../ simple_imp:host
../../../../buildTools/main_to_html_extensibella.py 3 host "Extensibella Example:  simple_imp:host" host_thms.xthm syntax.sos vars.sos typing.sos eval.sos
extensibella --compile host_thms.xthm
cd ..

cd list
sterling --extensibella -I ../../ simple_imp:list
../../../../buildTools/main_to_html_extensibella.py 3 list "Extensibella Example:  simple_imp:list" list_thms.xthm list.sos list_vars.sos list_typing.sos list_eval.sos
cd ..

cd security
sterling --extensibella -I ../../ simple_imp:security
../../../../buildTools/main_to_html_extensibella.py 3 security "Extensibella Example:  simple_imp:security" security_thms.xthm security.sos analysis.sos
cd ..

cd repeatWhile
sterling --extensibella -I ../../ simple_imp:repeatWhile
../../../../buildTools/main_to_html_extensibella.py 3 repeatWhile "Extensibella Example:  simple_imp:repeatWhile" repeatWhile_thms.xthm repeatWhile.sos
cd ..

cd assert
sterling --extensibella -I ../../ simple_imp:assert
../../../../buildTools/main_to_html_extensibella.py 3 assert "Extensibella Example:  simple_imp:assert" assert_thms.xthm assert.sos
cd ..
